/* vim: set tabstop=4 shiftwidth=4 softtabstop=4 expandtab smarttab : */
/**
 * @file   resource_sigscheme.cpp
 * @author Soo Han, Kim (princeb612.kr@gmail.com)
 * @desc
 *
 * Revision History
 * Date         Name                Description
 */

#include <hotplace/sdk/crypto/advisor/crypto_advisor.hpp>
#include <hotplace/sdk/io/system/sdk.hpp>
#include <iostream>

namespace hotplace {
namespace crypto {

extern const hint_sigscheme_t hint_sigschemes[] = {
    {
        tls_sigscheme_t::rsa_pkcs1_sha256,
        0x0301,
        tls_flag_support,
        "rsa_pkcs1_sha256",
        sig_category_t::rsassa_pkcs15,
        signature_t::rs256,
        kty_rsa,
        nid_rsa,
        hash_algorithm_t::sha2_256,
        {32},
    },
    {
        tls_sigscheme_t::rsa_pkcs1_sha384,
        0x0301,
        tls_flag_support,
        "rsa_pkcs1_sha384",
        sig_category_t::rsassa_pkcs15,
        signature_t::rs384,
        kty_rsa,
        nid_rsa,
        hash_algorithm_t::sha2_384,
        {48},
    },
    {
        tls_sigscheme_t::rsa_pkcs1_sha512,
        0x0301,
        tls_flag_support,
        "rsa_pkcs1_sha512",
        sig_category_t::rsassa_pkcs15,
        signature_t::rs512,
        kty_rsa,
        nid_rsa,
        hash_algorithm_t::sha2_512,
        {64},
    },
    {
        tls_sigscheme_t::ecdsa_secp256r1_sha256,
        0x0301,
        tls_flag_support,
        "ecdsa_secp256r1_sha256",
        sig_category_t::ecdsa,
        signature_t::es256,
        kty_ec,
        NID_X9_62_prime256v1,
        hash_algorithm_t::sha2_256,
        {32},
    },
    {
        tls_sigscheme_t::ecdsa_secp384r1_sha384,
        0x0301,
        tls_flag_support,
        "ecdsa_secp384r1_sha384",
        sig_category_t::ecdsa,
        signature_t::es384,
        kty_ec,
        NID_secp384r1,
        hash_algorithm_t::sha2_384,
        {48},
    },
    {
        tls_sigscheme_t::ecdsa_secp521r1_sha512,
        0x0301,
        tls_flag_support,
        "ecdsa_secp521r1_sha512",
        sig_category_t::ecdsa,
        signature_t::es512,
        kty_ec,
        NID_secp521r1,
        hash_algorithm_t::sha2_512,
        {64},
    },
    {
        tls_sigscheme_t::rsa_pss_rsae_sha256,
        0x0301,
        tls_flag_support,
        "rsa_pss_rsae_sha256",
        sig_category_t::rsassa_pss,
        signature_t::ps256,
        kty_rsa,
        nid_rsa,
        hash_algorithm_t::sha2_256,
        {32},
    },
    {
        tls_sigscheme_t::rsa_pss_rsae_sha384,
        0x0301,
        tls_flag_support,
        "rsa_pss_rsae_sha384",
        sig_category_t::rsassa_pss,
        signature_t::ps384,
        kty_rsa,
        nid_rsa,
        hash_algorithm_t::sha2_384,
        {48},
    },
    {
        tls_sigscheme_t::rsa_pss_rsae_sha512,
        0x0301,
        tls_flag_support,
        "rsa_pss_rsae_sha512",
        sig_category_t::rsassa_pss,
        signature_t::ps512,
        kty_rsa,
        nid_rsa,
        hash_algorithm_t::sha2_512,
        {64},
    },
    {
        tls_sigscheme_t::ed25519,
        0x0301,
        tls_flag_support,
        "ed25519",
        sig_category_t::eddsa,
        signature_t::eddsa,
        kty_okp,
        NID_ED25519,
        hash_algorithm_t{},
        {32},
    },
    {
        tls_sigscheme_t::ed448,
        0x0301,
        tls_flag_support,
        "ed448",
        sig_category_t::eddsa,
        signature_t::eddsa,
        kty_okp,
        NID_ED448,
        hash_algorithm_t{},
        {57},
    },
    {
        tls_sigscheme_t::rsa_pss_pss_sha256,
        0x0301,
        tls_flag_support,
        "rsa_pss_pss_sha256",
        sig_category_t::rsassa_pss,
        signature_t::ps256,
        kty_rsapss,
        nid_rsa,
        hash_algorithm_t::sha2_256,
        {32},
    },
    {
        tls_sigscheme_t::rsa_pss_pss_sha384,
        0x0301,
        tls_flag_support,
        "rsa_pss_pss_sha384",
        sig_category_t::rsassa_pss,
        signature_t::ps384,
        kty_rsapss,
        nid_rsa,
        hash_algorithm_t::sha2_384,
        {48},
    },
    {
        tls_sigscheme_t::rsa_pss_pss_sha512,
        0x0301,
        tls_flag_support,
        "rsa_pss_pss_sha512",
        sig_category_t::rsassa_pss,
        signature_t::ps512,
        kty_rsapss,
        nid_rsa,
        hash_algorithm_t::sha2_512,
        {64},
    },
    {
        tls_sigscheme_t::ecdsa_brainpoolP256r1tls13_sha256,
        0x0304,
        tls_flag_support,
        "ecdsa_brainpoolP256r1tls13_sha256",
        sig_category_t::ecdsa,
        signature_t::brainpool256,
        kty_ec,
        nid_brainpoolp256r1tls13,
        hash_algorithm_t::sha2_256,
        {32},
    },
    {
        tls_sigscheme_t::ecdsa_brainpoolP384r1tls13_sha384,
        0x0304,
        tls_flag_support,
        "ecdsa_brainpoolP384r1tls13_sha384",
        sig_category_t::ecdsa,
        signature_t::brainpool384,
        kty_ec,
        nid_brainpoolp384r1tls13,
        hash_algorithm_t::sha2_384,
        {48},
    },
    {
        tls_sigscheme_t::ecdsa_brainpoolP512r1tls13_sha512,
        0x0304,
        tls_flag_support,
        "ecdsa_brainpoolP512r1tls13_sha512",
        sig_category_t::ecdsa,
        signature_t::brainpool512,
        kty_ec,
        nid_brainpoolp512r1tls13,
        hash_algorithm_t::sha2_512,
        {64},
    },
    {
        tls_sigscheme_t::rsa_pkcs1_sha1,
        0x0301,
        0,
        "rsa_pkcs1_sha1",
        sig_category_t::rsassa_pkcs15,
        signature_t::rs1,
        kty_rsa,
        nid_rsa,
        hash_algorithm_t::sha1,
        {20},
    },
    {
        tls_sigscheme_t::ecdsa_sha1,
        0x0301,
        0,
        "ecdsa_sha1",
        sig_category_t::ecdsa,
        signature_t::sha1,
        kty_ec,
        0,
        hash_algorithm_t::sha1,
        {20},
    },
#if OPENSSL_VERSION_NUMBER >= 0x30500000L
    {
        tls_sigscheme_t::mldsa44,
        0x0304,
        tls_flag_support,
        "mldsa44",
        sig_category_t::mldsa,
        signature_t::mldsa44,
        kty_mldsa,
        nid_ml_dsa_44,
        hash_algorithm_t{},
        {2420, 2560, 1312},
    },
    {
        tls_sigscheme_t::mldsa65,
        0x0304,
        tls_flag_support,
        "mldsa65",
        sig_category_t::mldsa,
        signature_t::mldsa65,
        kty_mldsa,
        nid_ml_dsa_65,
        hash_algorithm_t{},
        {3309, 4032, 1952},
    },
    {
        tls_sigscheme_t::mldsa87,
        0x0304,
        tls_flag_support,
        "mldsa87",
        sig_category_t::mldsa,
        signature_t::mldsa87,
        kty_mldsa,
        nid_ml_dsa_87,
        hash_algorithm_t{},
        {4627, 4896, 2592},
    },
    {
        tls_sigscheme_t::slhdsa_sha2_128s,  // 0x0911,
        0x0304,
        tls_flag_support,
        "slhdsa_sha2_128s",
        sig_category_t::slhdsa,
        signature_t::slhdsa_sha2_128s,
        kty_slhdsa,
        nid_slhdsa_sha2_128s,
        hash_algorithm_t{},
        {7856, 64, 32},
    },
    {
        tls_sigscheme_t::slhdsa_sha2_128f,  // 0x0912,
        0x0304,
        tls_flag_support,
        "slhdsa_sha2_128f",
        sig_category_t::slhdsa,
        signature_t::slhdsa_sha2_128f,
        kty_slhdsa,
        nid_slhdsa_sha2_128f,
        hash_algorithm_t{},
        {17088, 64, 32},
    },
    {
        tls_sigscheme_t::slhdsa_sha2_192s,  // 0x0913,
        0x0304,
        tls_flag_support,
        "slhdsa_sha2_192s",
        sig_category_t::slhdsa,
        signature_t::slhdsa_sha2_192s,
        kty_slhdsa,
        nid_slhdsa_sha2_192s,
        hash_algorithm_t{},
        {16224, 96, 48},
    },
    {
        tls_sigscheme_t::slhdsa_sha2_192f,  // 0x0914,
        0x0304,
        tls_flag_support,
        "slhdsa_sha2_192f",
        sig_category_t::slhdsa,
        signature_t::slhdsa_sha2_192f,
        kty_slhdsa,
        nid_slhdsa_sha2_192f,
        hash_algorithm_t{},
        {35664, 96, 48},
    },
    {
        tls_sigscheme_t::slhdsa_sha2_256s,  // 0x0915,
        0x0304,
        tls_flag_support,
        "slhdsa_sha2_256s",
        sig_category_t::slhdsa,
        signature_t::slhdsa_sha2_256s,
        kty_slhdsa,
        nid_slhdsa_sha2_256s,
        hash_algorithm_t{},
        {29792, 128, 64},
    },
    {
        tls_sigscheme_t::slhdsa_sha2_256f,  // 0x0916,
        0x0304,
        tls_flag_support,
        "slhdsa_sha2_256f",
        sig_category_t::slhdsa,
        signature_t::slhdsa_sha2_256f,
        kty_slhdsa,
        nid_slhdsa_sha2_256f,
        hash_algorithm_t{},
        {49856, 128, 64},
    },
    {
        tls_sigscheme_t::slhdsa_shake_128s,  // 0x0917,
        0x0304,
        tls_flag_support,
        "slhdsa_shake_128s",
        sig_category_t::slhdsa,
        signature_t::slhdsa_shake_128s,
        kty_slhdsa,
        nid_slhdsa_shake_128s,
        hash_algorithm_t{},
        {7856, 64, 32},
    },
    {
        tls_sigscheme_t::slhdsa_shake_128f,  // 0x0918,
        0x0304,
        tls_flag_support,
        "slhdsa_shake_128f",
        sig_category_t::slhdsa,
        signature_t::slhdsa_shake_128f,
        kty_slhdsa,
        nid_slhdsa_shake_128f,
        hash_algorithm_t{},
        {17088, 64, 32},
    },
    {
        tls_sigscheme_t::slhdsa_shake_192s,  // 0x0919,
        0x0304,
        tls_flag_support,
        "slhdsa_shake_192s",
        sig_category_t::slhdsa,
        signature_t::slhdsa_shake_192s,
        kty_slhdsa,
        nid_slhdsa_shake_192s,
        hash_algorithm_t{},
        {16224, 96, 48},
    },
    {
        tls_sigscheme_t::slhdsa_shake_192f,  // 0x091A,
        0x0304,
        tls_flag_support,
        "slhdsa_shake_192f",
        sig_category_t::slhdsa,
        signature_t::slhdsa_shake_192f,
        kty_slhdsa,
        nid_slhdsa_shake_192f,
        hash_algorithm_t{},
        {35664, 96, 48},
    },
    {
        tls_sigscheme_t::slhdsa_shake_256s,  // 0x091B,
        0x0304,
        tls_flag_support,
        "slhdsa_shake_256s",
        sig_category_t::slhdsa,
        signature_t::slhdsa_shake_256s,
        kty_slhdsa,
        nid_slhdsa_shake_256s,
        hash_algorithm_t{},
        {29792, 128, 64},
    },
    {
        tls_sigscheme_t::slhdsa_shake_256f,  // 0x091C,
        0x0304,
        tls_flag_support,
        "slhdsa_shake_256f",
        sig_category_t::slhdsa,
        signature_t::slhdsa_shake_256f,
        kty_slhdsa,
        nid_slhdsa_shake_256f,
        hash_algorithm_t{},
        {49856, 128, 64},
    },
#endif
};

extern const size_t sizeof_hint_sigschemes = RTL_NUMBER_OF(hint_sigschemes);

}  // namespace crypto
}  // namespace hotplace
