/* vim: set tabstop=4 parser_action_t::shiftwidth=4 softtabstop=4 expandtab smarttab : */
/**
 * @file   asn1_lalr_productions.cpp
 * @author Soo Han, Kim (princeb612.kr@gmail.com)
 * @desc
 *
 * Revision History
 * Date         Name                Description
 *
 * see README.md
 */

#include <hotplace/sdk/io/asn.1/asn1_resource.hpp>

namespace hotplace {
namespace io {

// clang-format off
const std::vector<parser_production> asn1_productions = //
{
 {0, "S\'", {"Statement"}},
 {1, "Statement", {"Assignment"}},
 {2, "Statement", {"TypeSpec"}},
 {3, "Statement", {"Constraint"}},
 {4, "Statement", {"Field"}},
 {5, "Statement", {"TagPrefix"}},
 {6, "Assignment", {"DefinedType", "::=", "TypeSpec"}},
 {7, "Assignment", {"DefinedType", "::=", "TypeSpec", "Constraint"}},
 {8, "DefinedType", {SYMBOL_USERTYPE}},
 {9, "DefinedType", {SYMBOL_ID}},
 {10, "StatementSequence", {"SEQUENCE", "Constraint", "{", "FieldList", "}"}},
 {11, "StatementSequence", {"SEQUENCE", "{", "FieldList", "}"}},
 {12, "StatementSequence", {"SEQUENCE", "Constraint", "{", "}"}},
 {13, "StatementSequence", {"SEQUENCE", "{", "}"}},
 {14, "StatementSequenceOf", {"SEQUENCE", "SizeConstraint", "OF", "TypeSpec"}},
 {15, "StatementSequenceOf", {"SEQUENCE", "Constraint", "OF", "TypeSpec"}},
 {16, "StatementSequenceOf", {"SEQUENCE", "OF", "TypeSpec"}},
 {17, "StatementSet", {"SET", "Constraint", "{", "FieldList", "}"}},
 {18, "StatementSet", {"SET", "{", "FieldList", "}"}},
 {19, "StatementSet", {"SET", "Constraint", "{", "}"}},
 {20, "StatementSet", {"SET", "{", "}"}},
 {21, "StatementSetOf", {"SET", "SizeConstraint", "OF", "TypeSpec"}},
 {22, "StatementSetOf", {"SET", "Constraint", "OF", "TypeSpec"}},
 {23, "StatementSetOf", {"SET", "OF", "TypeSpec"}},
 {24, "StatementChoice", {"CHOICE", "Constraint", "{", "FieldList", "}"}},
 {25, "StatementChoice", {"CHOICE", "{", "FieldList", "}"}},
 {26, "StatementChoice", {"CHOICE", "Constraint", "{", "}"}},
 {27, "StatementChoice", {"CHOICE", "{", "}"}},
 {28, "FieldList", {"FieldList", ",", "Field"}},
 {29, "FieldList", {"Field"}},
 {30, "Field", {SYMBOL_ID, "TypeSpec"}},
 {31, "Field", {SYMBOL_ID, "TypeSpec", "Constraint"}},
 {32, "Field", {SYMBOL_ID, "TypeSpec", "FieldOpt"}},
 {33, "Field", {SYMBOL_ID, "TypeSpec", "Constraint", "FieldOpt"}},
 {34, "Field", {SYMBOL_USERTYPE, "TypeSpec"}},
 {35, "Field", {SYMBOL_USERTYPE, "TypeSpec", "Constraint"}},
 {36, "Field", {SYMBOL_USERTYPE, "TypeSpec", "FieldOpt"}},
 {37, "Field", {SYMBOL_USERTYPE, "TypeSpec", "Constraint", "FieldOpt"}},
 {38, "FieldOpt", {"OPTIONAL"}},
 {39, "FieldOpt", {"DEFAULT", SYMBOL_NUM}},
 {40, "FieldOpt", {"DEFAULT", SYMBOL_QSTR}},
 {41, "FieldOpt", {"DEFAULT", "{", "}"}},
 {42, "TypeSpec", {"TypeBase"}},
 {43, "TypeSpec", {"EnumType"}},
 {44, "TypeSpec", {"StatementSequence"}},
 {45, "TypeSpec", {"StatementSequenceOf"}},
 {46, "TypeSpec", {"StatementSet"}},
 {47, "TypeSpec", {"StatementSetOf"}},
 {48, "TypeSpec", {"StatementChoice"}},
 {49, "TypeBase", {"SimpleType"}},
 {50, "TypeBase", {"TaggedType"}},
 {51, "TypeBase", {"ReferencedType"}},
 {52, "ReferencedType", {SYMBOL_USERTYPE}},
 {53, "ReferencedType", {SYMBOL_ID}},
 {54, "TaggedType", {"TagPrefix", "TagSpec", "TypeSpec"}},
 {55, "TaggedType", {"TagPrefix", "TypeSpec"}},
 {56, "TagPrefix", {"[", "TagClass", SYMBOL_NUM, "]"}},
 {57, "TagPrefix", {"[", SYMBOL_NUM, "]"}},
 {58, "TagClass", {"UNIVERSAL"}},
 {59, "TagClass", {"APPLICATION"}},
 {60, "TagClass", {"PRIVATE"}},
 {61, "TagSpec", {"IMPLICIT"}},
 {62, "TagSpec", {"EXPLICIT"}},
 {63, "EnumType", {"ENUMERATED", "{", "EnumList", "}"}},
 {64, "EnumList", {"EnumList", ",", "EnumItem"}},
 {65, "EnumList", {"EnumItem"}},
 {66, "EnumItem", {SYMBOL_ID, "(", SYMBOL_NUM, ")"}},
 {67, "SimpleType", {"BOOLEAN"}},
 {68, "SimpleType", {"INTEGER"}},
 {69, "SimpleType", {"INTEGER", "{", "EnumList", "}"}},
 {70, "SimpleType", {"BIT STRING"}},
 {71, "SimpleType", {"BIT STRING", "{", "EnumList", "}"}},
 {72, "SimpleType", {"OCTET STRING"}},
 {73, "SimpleType", {"NULL"}},
 {74, "SimpleType", {"OBJECT IDENTIFIER"}},
 {75, "SimpleType", {"REAL"}},
 {76, "SimpleType", {"UTF8String"}},
 {77, "SimpleType", {"RELATIVE-OID"}},
 {78, "SimpleType", {"TIME"}},
 {79, "SimpleType", {"NumericString"}},
 {80, "SimpleType", {"PrintableString"}},
 {81, "SimpleType", {"TeletexString"}},
 {82, "SimpleType", {"T61String"}},
 {83, "SimpleType", {"VideotexString"}},
 {84, "SimpleType", {"IA5String"}},
 {85, "SimpleType", {"UTCTime"}},
 {86, "SimpleType", {"GeneralizedTime"}},
 {87, "SimpleType", {"GraphicString"}},
 {88, "SimpleType", {"VisibleString"}},
 {89, "SimpleType", {"ISO646String"}},
 {90, "SimpleType", {"GeneralString"}},
 {91, "SimpleType", {"UniversalString"}},
 {92, "SimpleType", {"CHARACTER STRING"}},
 {93, "SimpleType", {"BMPString"}},
 {94, "SimpleType", {"DATE"}},
 {95, "SimpleType", {"TIME-OF-DAY"}},
 {96, "SimpleType", {"DATE-TIME"}},
 {97, "SimpleType", {"DURATION"}},
 {98, "SimpleType", {"ANY"}},
 {99, "Constraint", {"(", "ConstraintExpr", ")"}},
 {100, "ConstraintExpr", {"SubtypeElementSet"}},
 {101, "ConstraintExpr", {"ALL EXCEPT", "SubtypeElementSet"}},
 {102, "SubtypeElementSet", {"SubtypeElementSet", "|", "SubtypeElement"}},
 {103, "SubtypeElementSet", {"SubtypeElementSet", ",", "SubtypeElement"}},
 {104, "SubtypeElementSet", {"SubtypeElementSet", "UNION", "SubtypeElement"}},
 {105, "SubtypeElementSet", {"SubtypeElementSet", "EXCEPT", "SubtypeElement"}},
 {106, "SubtypeElementSet", {"SubtypeElementSet", "SubtypeElement"}},
 {107, "SubtypeElementSet", {"SubtypeElement"}},
 {108, "SubtypeElement", {"SubtypeElement", "^", "PrimaryElement"}},
 {109, "SubtypeElement", {"SubtypeElement", "INTERSECTION", "PrimaryElement"}},
 {110, "SubtypeElement", {"PrimaryElement"}},
 {111, "PrimaryElement", {"ValueElement"}},
 {112, "PrimaryElement", {"ValueElement", "..", "ValueElement"}},
 {113, "PrimaryElement", {"ValueElement", "..", "<", "ValueElement"}},
 {114, "PrimaryElement", {"ValueElement", "<", "..", "ValueElement"}},
 {115, "PrimaryElement", {"ValueElement", "<", "..", "<", "ValueElement"}},
 {116, "PrimaryElement", {"SIZE", "Constraint"}},
 {117, "PrimaryElement", {"FROM", "Constraint"}},
 {118, "PrimaryElement", {"PATTERN", SYMBOL_QSTR}},
 {119, "PrimaryElement", {"(", "ConstraintExpr", ")"}},
 {120, "SizeConstraint", {"SIZE", "Constraint"}},
 {121, "ValueElement", {SYMBOL_ID}},
 {122, "ValueElement", {SYMBOL_USERTYPE}},
 {123, "ValueElement", {SYMBOL_NUM}},
 {124, "ValueElement", {SYMBOL_FP}},
 {125, "ValueElement", {SYMBOL_QSTR}},
 {126, "ValueElement", {"MIN"}},
 {127, "ValueElement", {"MAX"}},
 {128, "ValueElement", {"TRUE"}},
 {129, "ValueElement", {"FALSE"}},
};
// clang-format on

}  // namespace io
}  // namespace hotplace
