/* vim: set tabstop=4 parser_action_t::shiftwidth=4 softtabstop=4 expandtab smarttab : */
/**
 * @file   asn1_notation_productions.cpp
 * @author Soo Han, Kim (princeb612.kr@gmail.com)
 * @desc
 *
 * Revision History
 * Date         Name                Description
 *
 * see README.md
 */

#include <hotplace/sdk/io/asn.1/asn1_resource.hpp>

namespace hotplace {
namespace io {

// clang-format off
const std::vector<parser_production> asn1_allin1_productions = //
{
 {0, "S'", {"Statement"}},
 {1, "Statement", {"Assignment"}},
 {2, "Statement", {"TypeSpec"}},
 {3, "Statement", {"Constraint"}},
 {4, "Statement", {"Field"}},
 {5, "Statement", {"TagPrefix"}},
 {6, "Assignment", {"userparamtype", "{", "TemplateParamList", "}", "::=", "TypeSpec"}},
 {7, "Assignment", {"userparamtype", "{", "TemplateParamList", "}", "::=", "TypeSpec", "Constraint"}},
 {8, "Assignment", {"DefinedType", "::=", "TypeSpec"}},
 {9, "Assignment", {"DefinedType", "::=", "TypeSpec", "Constraint"}},
 {10, "DefinedType", {SYMBOL_USERTYPE}},
 {11, "TemplateParamList", {"TemplateParamList", ",", "TemplateParam"}},
 {12, "TemplateParamList", {"TemplateParam"}},
 {13, "TemplateParam", {"paramtype"}},
 {14, "TemplateParam", {"TypeSpec", ":", "paramvalue"}},
 {15, "TemplateParam", {"paramtype", ":", "paramvalue"}},
 {16, "SequenceTypeSpec", {"SEQUENCE", "Constraint", "{", "FieldList", "}"}},
 {17, "SequenceTypeSpec", {"SEQUENCE", "{", "FieldList", "}"}},
 {18, "SequenceTypeSpec", {"SEQUENCE", "Constraint", "{", "}"}},
 {19, "SequenceTypeSpec", {"SEQUENCE", "{", "}"}},
 {20, "SequenceOfTypeSpec", {"SEQUENCE", "SizeConstraint", "OF", "TypeSpec"}},
 {21, "SequenceOfTypeSpec", {"SEQUENCE", "Constraint", "OF", "TypeSpec"}},
 {22, "SequenceOfTypeSpec", {"SEQUENCE", "OF", "TypeSpec"}},
 {23, "SetTypeSpec", {"SET", "Constraint", "{", "FieldList", "}"}},
 {24, "SetTypeSpec", {"SET", "{", "FieldList", "}"}},
 {25, "SetTypeSpec", {"SET", "Constraint", "{", "}"}},
 {26, "SetTypeSpec", {"SET", "{", "}"}},
 {27, "SetOfTypeSpec", {"SET", "SizeConstraint", "OF", "TypeSpec"}},
 {28, "SetOfTypeSpec", {"SET", "Constraint", "OF", "TypeSpec"}},
 {29, "SetOfTypeSpec", {"SET", "OF", "TypeSpec"}},
 {30, "ChoiceTypeSpec", {"CHOICE", "Constraint", "{", "FieldList", "}"}},
 {31, "ChoiceTypeSpec", {"CHOICE", "{", "FieldList", "}"}},
 {32, "ChoiceTypeSpec", {"CHOICE", "Constraint", "{", "}"}},
 {33, "ChoiceTypeSpec", {"CHOICE", "{", "}"}},
 {34, "FieldList", {"FieldList", ",", "Field"}},
 {35, "FieldList", {"Field"}},
 {36, "Field", {SYMBOL_ID, "TypeSpec"}},
 {37, "Field", {SYMBOL_ID, "TypeSpec", "Constraint"}},
 {38, "Field", {SYMBOL_ID, "TypeSpec", "FieldSpecifier"}},
 {39, "Field", {SYMBOL_ID, "TypeSpec", "Constraint", "FieldSpecifier"}},
 {40, "FieldSpecifier", {"OPTIONAL"}},
 {41, "FieldSpecifier", {"DEFAULT", "ValueElement"}},
 {42, "FieldSpecifier", {"DEFAULT", "{", "}"}},
 {43, "TypeSpec", {"SimpleTypeSpec"}},
 {44, "TypeSpec", {"TaggedTypeSpec"}},
 {45, "TypeSpec", {"ReferencedTypeSpec"}},
 {46, "TypeSpec", {"EnumTypeSpec"}},
 {47, "TypeSpec", {"SequenceTypeSpec"}},
 {48, "TypeSpec", {"SequenceOfTypeSpec"}},
 {49, "TypeSpec", {"SetTypeSpec"}},
 {50, "TypeSpec", {"SetOfTypeSpec"}},
 {51, "TypeSpec", {"ChoiceTypeSpec"}},
 {52, "ReferencedTypeSpec", {"Identifier"}},
 {53, "ReferencedTypeSpec", {"paramtype"}},
 {54, "ReferencedTypeSpec", {"userparamtype", "{", "TemplateArgumentList", "}"}},
 {55, "ReferencedTypeSpec", {SYMBOL_ID, "{", "TemplateArgumentList", "}"}},
 {56, "TemplateArgumentList", {"TemplateArgumentList", ",", "TemplateArgument"}},
 {57, "TemplateArgumentList", {"TemplateArgument"}},
 {58, "TemplateArgument", {"TypeSpec"}},
 {59, "TemplateArgument", {SYMBOL_NUM}},
 {60, "TemplateArgument", {SYMBOL_FP}},
 {61, "TemplateArgument", {SYMBOL_QSTR}},
 {62, "TemplateArgument", {"TRUE"}},
 {63, "TemplateArgument", {"FALSE"}},
 {64, "TaggedTypeSpec", {"TagPrefix", "TagSpec", "TypeSpec"}},
 {65, "TaggedTypeSpec", {"TagPrefix", "TypeSpec"}},
 {66, "TagPrefix", {"[", "TagClass", SYMBOL_NUM, "]"}},
 {67, "TagPrefix", {"[", SYMBOL_NUM, "]"}},
 {68, "TagClass", {"UNIVERSAL"}},
 {69, "TagClass", {"APPLICATION"}},
 {70, "TagClass", {"PRIVATE"}},
 {71, "TagSpec", {"IMPLICIT"}},
 {72, "TagSpec", {"EXPLICIT"}},
 {73, "EnumTypeSpec", {"ENUMERATED", "{", "EnumList", "}"}},
 {74, "EnumList", {"EnumList", ",", "EnumItem"}},
 {75, "EnumList", {"EnumItem"}},
 {76, "EnumItem", {SYMBOL_ID, "(", SYMBOL_NUM, ")"}},
 {77, "SimpleTypeSpec", {"BOOLEAN"}},
 {78, "SimpleTypeSpec", {"INTEGER"}},
 {79, "SimpleTypeSpec", {"INTEGER", "{", "EnumList", "}"}},
 {80, "SimpleTypeSpec", {"BIT STRING"}},
 {81, "SimpleTypeSpec", {"BIT STRING", "{", "EnumList", "}"}},
 {82, "SimpleTypeSpec", {"OCTET STRING"}},
 {83, "SimpleTypeSpec", {"NULL"}},
 {84, "SimpleTypeSpec", {"OBJECT IDENTIFIER"}},
 {85, "SimpleTypeSpec", {"REAL"}},
 {86, "SimpleTypeSpec", {"UTF8String"}},
 {87, "SimpleTypeSpec", {"RELATIVE-OID"}},
 {88, "SimpleTypeSpec", {"TIME"}},
 {89, "SimpleTypeSpec", {"NumericString"}},
 {90, "SimpleTypeSpec", {"PrintableString"}},
 {91, "SimpleTypeSpec", {"TeletexString"}},
 {92, "SimpleTypeSpec", {"T61String"}},
 {93, "SimpleTypeSpec", {"VideotexString"}},
 {94, "SimpleTypeSpec", {"IA5String"}},
 {95, "SimpleTypeSpec", {"UTCTime"}},
 {96, "SimpleTypeSpec", {"GeneralizedTime"}},
 {97, "SimpleTypeSpec", {"GraphicString"}},
 {98, "SimpleTypeSpec", {"VisibleString"}},
 {99, "SimpleTypeSpec", {"ISO646String"}},
 {100, "SimpleTypeSpec", {"GeneralString"}},
 {101, "SimpleTypeSpec", {"UniversalString"}},
 {102, "SimpleTypeSpec", {"CHARACTER STRING"}},
 {103, "SimpleTypeSpec", {"BMPString"}},
 {104, "SimpleTypeSpec", {"DATE"}},
 {105, "SimpleTypeSpec", {"TIME-OF-DAY"}},
 {106, "SimpleTypeSpec", {"DATE-TIME"}},
 {107, "SimpleTypeSpec", {"DURATION"}},
 {108, "SimpleTypeSpec", {"ANY"}},
 {109, "Constraint", {"(", "ConstraintExpr", ")"}},
 {110, "ConstraintExpr", {"SubtypeElementSet"}},
 {111, "ConstraintExpr", {"ALL EXCEPT", "SubtypeElementSet"}},
 {112, "SubtypeElementSet", {"SubtypeElementSet", "|", "SubtypeElement"}},
 {113, "SubtypeElementSet", {"SubtypeElementSet", ",", "SubtypeElement"}},
 {114, "SubtypeElementSet", {"SubtypeElementSet", "UNION", "SubtypeElement"}},
 {115, "SubtypeElementSet", {"SubtypeElementSet", "EXCEPT", "SubtypeElement"}},
 {116, "SubtypeElementSet", {"SubtypeElementSet", "SubtypeElement"}},
 {117, "SubtypeElementSet", {"SubtypeElement"}},
 {118, "SubtypeElement", {"SubtypeElement", "^", "PrimaryElement"}},
 {119, "SubtypeElement", {"SubtypeElement", "INTERSECTION", "PrimaryElement"}},
 {120, "SubtypeElement", {"PrimaryElement"}},
 {121, "PrimaryElement", {"ValueElement"}},
 {122, "PrimaryElement", {"ValueElement", "..", "ValueElement"}},
 {123, "PrimaryElement", {"ValueElement", "..", "<", "ValueElement"}},
 {124, "PrimaryElement", {"ValueElement", "<", "..", "ValueElement"}},
 {125, "PrimaryElement", {"ValueElement", "<", "..", "<", "ValueElement"}},
 {126, "PrimaryElement", {"SIZE", "Constraint"}},
 {127, "PrimaryElement", {"FROM", "Constraint"}},
 {128, "PrimaryElement", {"PATTERN", SYMBOL_QSTR}},
 {129, "PrimaryElement", {"(", "ConstraintExpr", ")"}},
 {130, "SizeConstraint", {"SIZE", "Constraint"}},
 {131, "Identifier", {SYMBOL_USERTYPE}},
 {132, "Identifier", {SYMBOL_ID}},
 {133, "ValueElement", {"paramvalue"}},
 {134, "ValueElement", {SYMBOL_NUM}},
 {135, "ValueElement", {SYMBOL_FP}},
 {136, "ValueElement", {SYMBOL_QSTR}},
 {137, "ValueElement", {"MIN"}},
 {138, "ValueElement", {"MAX"}},
 {139, "ValueElement", {"TRUE"}},
 {140, "ValueElement", {"FALSE"}},
};
// clang-format on

}  // namespace io
}  // namespace hotplace
