/* vim: set tabstop=4 parser_action_t::shiftwidth=4 softtabstop=4 expandtab smarttab : */
/**
 * @file   asn1_module_action.cpp
 * @author Soo Han, Kim (princeb612.kr@gmail.com)
 * @desc
 *
 * Revision History
 * Date         Name                Description
 *
 * see README.md
 */

#include <hotplace/sdk/io/asn.1/asn1_resource.hpp>

namespace hotplace {
namespace io {

// clang-format off
const std::map<std::pair<uint32, std::string>, parser_action> asn1_module_action_table =  //
{
 {{0, SYMBOL_ID}, {parser_action_t::shift, 4}},
 {{0, SYMBOL_USERTYPE}, {parser_action_t::shift, 5}},
 {{1, "$"}, {parser_action_t::accept, 0}},
 {{2, "...."}, {parser_action_t::shift, 6}},
 {{2, "EXPORTS"}, {parser_action_t::shift, 7}},
 {{2, "IMPORTS"}, {parser_action_t::shift, 9}},
 {{2, "Statement"}, {parser_action_t::shift, 12}},
 {{3, "DEFINITIONS"}, {parser_action_t::shift, 13}},
 {{3, "{"}, {parser_action_t::shift, 14}},
 {{4, ";"}, {parser_action_t::reduce, 13}},
 {{4, "DEFINITIONS"}, {parser_action_t::reduce, 13}},
 {{4, "{"}, {parser_action_t::reduce, 13}},
 {{5, ";"}, {parser_action_t::reduce, 12}},
 {{5, "DEFINITIONS"}, {parser_action_t::reduce, 12}},
 {{5, "{"}, {parser_action_t::reduce, 12}},
 {{6, "END"}, {parser_action_t::reduce, 22}},
 {{7, "ALL"}, {parser_action_t::shift, 15}},
 {{7, SYMBOL_ID}, {parser_action_t::shift, 18}},
 {{7, SYMBOL_USERTYPE}, {parser_action_t::shift, 19}},
 {{8, "...."}, {parser_action_t::reduce, 18}},
 {{8, "IMPORTS"}, {parser_action_t::shift, 9}},
 {{8, "Statement"}, {parser_action_t::reduce, 18}},
 {{9, SYMBOL_ID}, {parser_action_t::shift, 18}},
 {{9, SYMBOL_USERTYPE}, {parser_action_t::shift, 19}},
 {{10, "...."}, {parser_action_t::reduce, 19}},
 {{10, "EXPORTS"}, {parser_action_t::shift, 7}},
 {{10, "Statement"}, {parser_action_t::reduce, 19}},
 {{11, "...."}, {parser_action_t::shift, 6}},
 {{11, "Statement"}, {parser_action_t::shift, 25}},
 {{12, "END"}, {parser_action_t::shift, 26}},
 {{13, "::="}, {parser_action_t::shift, 27}},
 {{13, "AUTOMATIC"}, {parser_action_t::shift, 28}},
 {{13, "EXPLICIT"}, {parser_action_t::shift, 29}},
 {{13, "IMPLICIT"}, {parser_action_t::shift, 30}},
 {{14, SYMBOL_ID}, {parser_action_t::shift, 34}},
 {{15, ";"}, {parser_action_t::shift, 35}},
 {{16, ","}, {parser_action_t::reduce, 30}},
 {{16, ";"}, {parser_action_t::reduce, 30}},
 {{16, "FROM"}, {parser_action_t::reduce, 30}},
 {{17, ","}, {parser_action_t::shift, 36}},
 {{17, ";"}, {parser_action_t::shift, 37}},
 {{18, ","}, {parser_action_t::reduce, 32}},
 {{18, ";"}, {parser_action_t::reduce, 32}},
 {{18, "FROM"}, {parser_action_t::reduce, 32}},
 {{18, "{"}, {parser_action_t::shift, 38}},
 {{19, ","}, {parser_action_t::reduce, 31}},
 {{19, ";"}, {parser_action_t::reduce, 31}},
 {{19, "FROM"}, {parser_action_t::reduce, 31}},
 {{19, "{"}, {parser_action_t::shift, 39}},
 {{20, "...."}, {parser_action_t::reduce, 20}},
 {{20, "Statement"}, {parser_action_t::reduce, 20}},
 {{21, ","}, {parser_action_t::shift, 36}},
 {{21, "FROM"}, {parser_action_t::shift, 40}},
 {{22, ";"}, {parser_action_t::reduce, 26}},
 {{23, ";"}, {parser_action_t::shift, 41}},
 {{24, "...."}, {parser_action_t::reduce, 21}},
 {{24, "Statement"}, {parser_action_t::reduce, 21}},
 {{25, "END"}, {parser_action_t::shift, 42}},
 {{26, "$"}, {parser_action_t::reduce, 2}},
 {{27, "BEGIN"}, {parser_action_t::shift, 43}},
 {{28, "TAGS"}, {parser_action_t::shift, 44}},
 {{29, "TAGS"}, {parser_action_t::shift, 45}},
 {{30, "TAGS"}, {parser_action_t::shift, 46}},
 {{31, "::="}, {parser_action_t::shift, 47}},
 {{31, "EXTENSIBILITY"}, {parser_action_t::shift, 48}},
 {{32, SYMBOL_ID}, {parser_action_t::reduce, 4}},
 {{32, "}"}, {parser_action_t::reduce, 4}},
 {{33, SYMBOL_ID}, {parser_action_t::shift, 34}},
 {{33, "}"}, {parser_action_t::shift, 51}},
 {{34, "("}, {parser_action_t::shift, 52}},
 {{35, "...."}, {parser_action_t::reduce, 24}},
 {{35, "IMPORTS"}, {parser_action_t::reduce, 24}},
 {{35, "Statement"}, {parser_action_t::reduce, 24}},
 {{36, SYMBOL_ID}, {parser_action_t::shift, 18}},
 {{36, SYMBOL_USERTYPE}, {parser_action_t::shift, 19}},
 {{37, "...."}, {parser_action_t::reduce, 23}},
 {{37, "IMPORTS"}, {parser_action_t::reduce, 23}},
 {{37, "Statement"}, {parser_action_t::reduce, 23}},
 {{38, "}"}, {parser_action_t::shift, 54}},
 {{39, "}"}, {parser_action_t::shift, 55}},
 {{40, SYMBOL_ID}, {parser_action_t::shift, 4}},
 {{40, SYMBOL_USERTYPE}, {parser_action_t::shift, 5}},
 {{41, "...."}, {parser_action_t::reduce, 25}},
 {{41, "EXPORTS"}, {parser_action_t::reduce, 25}},
 {{41, "Statement"}, {parser_action_t::reduce, 25}},
 {{42, "$"}, {parser_action_t::reduce, 1}},
 {{43, "...."}, {parser_action_t::reduce, 8}},
 {{43, "EXPORTS"}, {parser_action_t::reduce, 8}},
 {{43, "IMPORTS"}, {parser_action_t::reduce, 8}},
 {{43, "Statement"}, {parser_action_t::reduce, 8}},
 {{44, "::="}, {parser_action_t::reduce, 16}},
 {{44, "EXTENSIBILITY"}, {parser_action_t::reduce, 16}},
 {{45, "::="}, {parser_action_t::reduce, 14}},
 {{45, "EXTENSIBILITY"}, {parser_action_t::reduce, 14}},
 {{46, "::="}, {parser_action_t::reduce, 15}},
 {{46, "EXTENSIBILITY"}, {parser_action_t::reduce, 15}},
 {{47, "BEGIN"}, {parser_action_t::shift, 57}},
 {{48, "IMPLIED"}, {parser_action_t::shift, 58}},
 {{49, "::="}, {parser_action_t::shift, 59}},
 {{50, SYMBOL_ID}, {parser_action_t::reduce, 3}},
 {{50, "}"}, {parser_action_t::reduce, 3}},
 {{51, "DEFINITIONS"}, {parser_action_t::shift, 60}},
 {{52, SYMBOL_NUM}, {parser_action_t::shift, 61}},
 {{53, ","}, {parser_action_t::reduce, 29}},
 {{53, ";"}, {parser_action_t::reduce, 29}},
 {{53, "FROM"}, {parser_action_t::reduce, 29}},
 {{54, ","}, {parser_action_t::reduce, 34}},
 {{54, ";"}, {parser_action_t::reduce, 34}},
 {{54, "FROM"}, {parser_action_t::reduce, 34}},
 {{55, ","}, {parser_action_t::reduce, 33}},
 {{55, ";"}, {parser_action_t::reduce, 33}},
 {{55, "FROM"}, {parser_action_t::reduce, 33}},
 {{56, ";"}, {parser_action_t::reduce, 27}},
 {{56, "{"}, {parser_action_t::shift, 62}},
 {{57, "...."}, {parser_action_t::reduce, 7}},
 {{57, "EXPORTS"}, {parser_action_t::reduce, 7}},
 {{57, "IMPORTS"}, {parser_action_t::reduce, 7}},
 {{57, "Statement"}, {parser_action_t::reduce, 7}},
 {{58, "::="}, {parser_action_t::reduce, 17}},
 {{59, "BEGIN"}, {parser_action_t::shift, 63}},
 {{60, "::="}, {parser_action_t::shift, 64}},
 {{60, "AUTOMATIC"}, {parser_action_t::shift, 28}},
 {{60, "EXPLICIT"}, {parser_action_t::shift, 29}},
 {{60, "IMPLICIT"}, {parser_action_t::shift, 30}},
 {{61, ")"}, {parser_action_t::shift, 66}},
 {{62, SYMBOL_ID}, {parser_action_t::shift, 34}},
 {{63, "...."}, {parser_action_t::reduce, 6}},
 {{63, "EXPORTS"}, {parser_action_t::reduce, 6}},
 {{63, "IMPORTS"}, {parser_action_t::reduce, 6}},
 {{63, "Statement"}, {parser_action_t::reduce, 6}},
 {{64, "BEGIN"}, {parser_action_t::shift, 68}},
 {{65, "::="}, {parser_action_t::shift, 69}},
 {{65, "EXTENSIBILITY"}, {parser_action_t::shift, 48}},
 {{66, SYMBOL_ID}, {parser_action_t::reduce, 5}},
 {{66, "}"}, {parser_action_t::reduce, 5}},
 {{67, SYMBOL_ID}, {parser_action_t::shift, 34}},
 {{67, "}"}, {parser_action_t::shift, 71}},
 {{68, "...."}, {parser_action_t::reduce, 11}},
 {{68, "EXPORTS"}, {parser_action_t::reduce, 11}},
 {{68, "IMPORTS"}, {parser_action_t::reduce, 11}},
 {{68, "Statement"}, {parser_action_t::reduce, 11}},
 {{69, "BEGIN"}, {parser_action_t::shift, 72}},
 {{70, "::="}, {parser_action_t::shift, 73}},
 {{71, ";"}, {parser_action_t::reduce, 28}},
 {{72, "...."}, {parser_action_t::reduce, 10}},
 {{72, "EXPORTS"}, {parser_action_t::reduce, 10}},
 {{72, "IMPORTS"}, {parser_action_t::reduce, 10}},
 {{72, "Statement"}, {parser_action_t::reduce, 10}},
 {{73, "BEGIN"}, {parser_action_t::shift, 74}},
 {{74, "...."}, {parser_action_t::reduce, 9}},
 {{74, "EXPORTS"}, {parser_action_t::reduce, 9}},
 {{74, "IMPORTS"}, {parser_action_t::reduce, 9}},
 {{74, "Statement"}, {parser_action_t::reduce, 9}},
};
// clang-format on

}  // namespace io
}  // namespace hotplace
