/* vim: set tabstop=4 parser_action_t::shiftwidth=4 softtabstop=4 expandtab smarttab : */
/**
 * @file   asn1_notation_productions.cpp
 * @author Soo Han, Kim (princeb612.kr@gmail.com)
 * @desc
 *
 * Revision History
 * Date         Name                Description
 *
 * see README.md
 */

#include <hotplace/sdk/io/asn.1/asn1_resource.hpp>

namespace hotplace {
namespace io {

// clang-format off
const std::vector<parser_production> asn1_notation_productions = //
{
 {0, "S'", {"Statement"}},
 {1, "Statement", {"Assignment"}},
 {2, "Statement", {"TypeSpec"}},
 {3, "Statement", {"Constraint"}},
 {4, "Statement", {"Field"}},
 {5, "Statement", {"TagPrefix"}},
 {6, "Assignment", {"DefinedType", "::=", "TypeSpec"}},
 {7, "Assignment", {"DefinedType", "::=", "TypeSpec", "Constraint"}},
 {8, "DefinedType", {SYMBOL_USERTYPE}},
 {9, "SequenceTypeSpec", {"SEQUENCE", "Constraint", "{", "FieldList", "}"}},
 {10, "SequenceTypeSpec", {"SEQUENCE", "{", "FieldList", "}"}},
 {11, "SequenceTypeSpec", {"SEQUENCE", "Constraint", "{", "}"}},
 {12, "SequenceTypeSpec", {"SEQUENCE", "{", "}"}},
 {13, "SequenceOfTypeSpec", {"SEQUENCE", "SizeConstraint", "OF", "TypeSpec"}},
 {14, "SequenceOfTypeSpec", {"SEQUENCE", "Constraint", "OF", "TypeSpec"}},
 {15, "SequenceOfTypeSpec", {"SEQUENCE", "OF", "TypeSpec"}},
 {16, "SetTypeSpec", {"SET", "Constraint", "{", "FieldList", "}"}},
 {17, "SetTypeSpec", {"SET", "{", "FieldList", "}"}},
 {18, "SetTypeSpec", {"SET", "Constraint", "{", "}"}},
 {19, "SetTypeSpec", {"SET", "{", "}"}},
 {20, "SetOfTypeSpec", {"SET", "SizeConstraint", "OF", "TypeSpec"}},
 {21, "SetOfTypeSpec", {"SET", "Constraint", "OF", "TypeSpec"}},
 {22, "SetOfTypeSpec", {"SET", "OF", "TypeSpec"}},
 {23, "ChoiceTypeSpec", {"CHOICE", "Constraint", "{", "FieldList", "}"}},
 {24, "ChoiceTypeSpec", {"CHOICE", "{", "FieldList", "}"}},
 {25, "ChoiceTypeSpec", {"CHOICE", "Constraint", "{", "}"}},
 {26, "ChoiceTypeSpec", {"CHOICE", "{", "}"}},
 {27, "FieldList", {"FieldList", ",", "Field"}},
 {28, "FieldList", {"Field"}},
 {29, "Field", {SYMBOL_ID, "TypeSpec"}},
 {30, "Field", {SYMBOL_ID, "TypeSpec", "Constraint"}},
 {31, "Field", {SYMBOL_ID, "TypeSpec", "FieldSpecifier"}},
 {32, "Field", {SYMBOL_ID, "TypeSpec", "Constraint", "FieldSpecifier"}},
 {33, "FieldSpecifier", {"OPTIONAL"}},
 {34, "FieldSpecifier", {"DEFAULT", SYMBOL_NUM}},
 {35, "FieldSpecifier", {"DEFAULT", SYMBOL_QSTR}},
 {36, "FieldSpecifier", {"DEFAULT", "{", "}"}},
 {37, "TypeSpec", {"SimpleTypeSpec"}},
 {38, "TypeSpec", {"TaggedTypeSpec"}},
 {39, "TypeSpec", {"ReferencedTypeSpec"}},
 {40, "TypeSpec", {"EnumTypeSpec"}},
 {41, "TypeSpec", {"SequenceTypeSpec"}},
 {42, "TypeSpec", {"SequenceOfTypeSpec"}},
 {43, "TypeSpec", {"SetTypeSpec"}},
 {44, "TypeSpec", {"SetOfTypeSpec"}},
 {45, "TypeSpec", {"ChoiceTypeSpec"}},
 {46, "ReferencedTypeSpec", {"Identifier"}},
 {47, "TaggedTypeSpec", {"TagPrefix", "TagSpec", "TypeSpec"}},
 {48, "TaggedTypeSpec", {"TagPrefix", "TypeSpec"}},
 {49, "TagPrefix", {"[", "TagClass", SYMBOL_NUM, "]"}},
 {50, "TagPrefix", {"[", SYMBOL_NUM, "]"}},
 {51, "TagClass", {"UNIVERSAL"}},
 {52, "TagClass", {"APPLICATION"}},
 {53, "TagClass", {"PRIVATE"}},
 {54, "TagSpec", {"IMPLICIT"}},
 {55, "TagSpec", {"EXPLICIT"}},
 {56, "EnumTypeSpec", {"ENUMERATED", "{", "EnumList", "}"}},
 {57, "EnumList", {"EnumList", ",", "EnumItem"}},
 {58, "EnumList", {"EnumItem"}},
 {59, "EnumItem", {SYMBOL_ID, "(", SYMBOL_NUM, ")"}},
 {60, "SimpleTypeSpec", {"BOOLEAN"}},
 {61, "SimpleTypeSpec", {"INTEGER"}},
 {62, "SimpleTypeSpec", {"INTEGER", "{", "EnumList", "}"}},
 {63, "SimpleTypeSpec", {"BIT STRING"}},
 {64, "SimpleTypeSpec", {"BIT STRING", "{", "EnumList", "}"}},
 {65, "SimpleTypeSpec", {"OCTET STRING"}},
 {66, "SimpleTypeSpec", {"NULL"}},
 {67, "SimpleTypeSpec", {"OBJECT IDENTIFIER"}},
 {68, "SimpleTypeSpec", {"REAL"}},
 {69, "SimpleTypeSpec", {"UTF8String"}},
 {70, "SimpleTypeSpec", {"RELATIVE-OID"}},
 {71, "SimpleTypeSpec", {"TIME"}},
 {72, "SimpleTypeSpec", {"NumericString"}},
 {73, "SimpleTypeSpec", {"PrintableString"}},
 {74, "SimpleTypeSpec", {"TeletexString"}},
 {75, "SimpleTypeSpec", {"T61String"}},
 {76, "SimpleTypeSpec", {"VideotexString"}},
 {77, "SimpleTypeSpec", {"IA5String"}},
 {78, "SimpleTypeSpec", {"UTCTime"}},
 {79, "SimpleTypeSpec", {"GeneralizedTime"}},
 {80, "SimpleTypeSpec", {"GraphicString"}},
 {81, "SimpleTypeSpec", {"VisibleString"}},
 {82, "SimpleTypeSpec", {"ISO646String"}},
 {83, "SimpleTypeSpec", {"GeneralString"}},
 {84, "SimpleTypeSpec", {"UniversalString"}},
 {85, "SimpleTypeSpec", {"CHARACTER STRING"}},
 {86, "SimpleTypeSpec", {"BMPString"}},
 {87, "SimpleTypeSpec", {"DATE"}},
 {88, "SimpleTypeSpec", {"TIME-OF-DAY"}},
 {89, "SimpleTypeSpec", {"DATE-TIME"}},
 {90, "SimpleTypeSpec", {"DURATION"}},
 {91, "SimpleTypeSpec", {"ANY"}},
 {92, "Constraint", {"(", "ConstraintExpr", ")"}},
 {93, "ConstraintExpr", {"SubtypeElementSet"}},
 {94, "ConstraintExpr", {"ALL EXCEPT", "SubtypeElementSet"}},
 {95, "SubtypeElementSet", {"SubtypeElementSet", "|", "SubtypeElement"}},
 {96, "SubtypeElementSet", {"SubtypeElementSet", ",", "SubtypeElement"}},
 {97, "SubtypeElementSet", {"SubtypeElementSet", "UNION", "SubtypeElement"}},
 {98, "SubtypeElementSet", {"SubtypeElementSet", "EXCEPT", "SubtypeElement"}},
 {99, "SubtypeElementSet", {"SubtypeElementSet", "SubtypeElement"}},
 {100, "SubtypeElementSet", {"SubtypeElement"}},
 {101, "SubtypeElement", {"SubtypeElement", "^", "PrimaryElement"}},
 {102, "SubtypeElement", {"SubtypeElement", "INTERSECTION", "PrimaryElement"}},
 {103, "SubtypeElement", {"PrimaryElement"}},
 {104, "PrimaryElement", {"ValueElement"}},
 {105, "PrimaryElement", {"ValueElement", "..", "ValueElement"}},
 {106, "PrimaryElement", {"ValueElement", "..", "<", "ValueElement"}},
 {107, "PrimaryElement", {"ValueElement", "<", "..", "ValueElement"}},
 {108, "PrimaryElement", {"ValueElement", "<", "..", "<", "ValueElement"}},
 {109, "PrimaryElement", {"SIZE", "Constraint"}},
 {110, "PrimaryElement", {"FROM", "Constraint"}},
 {111, "PrimaryElement", {"PATTERN", SYMBOL_QSTR}},
 {112, "PrimaryElement", {"(", "ConstraintExpr", ")"}},
 {113, "SizeConstraint", {"SIZE", "Constraint"}},
 {114, "Identifier", {SYMBOL_USERTYPE}},
 {115, "Identifier", {SYMBOL_ID}},
 {116, "ValueElement", {SYMBOL_NUM}},
 {117, "ValueElement", {SYMBOL_FP}},
 {118, "ValueElement", {SYMBOL_QSTR}},
 {119, "ValueElement", {"MIN"}},
 {120, "ValueElement", {"MAX"}},
 {121, "ValueElement", {"TRUE"}},
 {122, "ValueElement", {"FALSE"}},
};
// clang-format on

}  // namespace io
}  // namespace hotplace
